use_lockfile = false

[project]
name = "slurmtools"
r_version = "4.4"

repositories = [
    # use this to constantly be dealing with "whats next" - can always switch to pinned version"
    {alias = "ppm", url = "https://packagemanager.posit.co/cran/latest"},
    {alias = "prism", url = "https://prism.dev.a2-ai.cloud/rpkgs/stratus/2025-05-09"},
]

dependencies = [
    {name = "slurmtools", dependencies_only = true, path = ".", install_suggestions = true},
    "pkgbuild",
    "pkgdown",
    "rcmdcheck",
]

