model_number = '1001'
files_to_track = [ 'lst', 'ext', 'grd' ]
tmp_dir = '/tmp'
watched_dir = '/cluster-data/user-homes/matthews/Packages/slurmtools/vignettes/model/nonmem'
output_dir = '/cluster-data/user-homes/matthews/Packages/slurmtools/vignettes/model/nonmem/in_progress'
poll_duration = 1
alert = 'Slack'
level = 'Debug'
email = 'matthews@a2-ai.com'
threads = 1
topic = ''