# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Download mocked binaries
        run: |
          mkdir -p /usr/local/bin
          cd /tmp
          gh release download "sinfo/v0.2.1" -R a2-ai-tech-training/slurm-mocks -p "*Linux_x86_64.tar.gz" -D /usr/local/bin/
          tar -xvf /usr/local/bin/sinfo_Linux_x86_64.tar.gz
          mv ./sinfo /usr/local/bin/sinfo
          chmod 755 /usr/local/bin/sinfo

          gh release download "sacct/v0.2.0" -R a2-ai-tech-training/slurm-mocks -p "*Linux_x86_64.tar.gz" -D /usr/local/bin/
          tar -xvf /usr/local/bin/sacct_Linux_x86_64.tar.gz
          mv ./sacct /usr/local/bin/sacct
          chmod 755 /usr/local/bin/sacct

          gh release download "squeue/v0.2.1" -R a2-ai-tech-training/slurm-mocks -p "*Linux_x86_64.tar.gz" -D /usr/local/bin/
          tar -xvf /usr/local/bin/squeue_Linux_x86_64.tar.gz
          mv ./squeue /usr/local/bin/squeue
          chmod 755 /usr/local/bin/squeue

          gh release download "sbatch/v0.2.0" -R a2-ai-tech-training/slurm-mocks -p "*Linux_x86_64.tar.gz" -D /usr/local/bin/
          tar -xvf /usr/local/bin/sbatch_Linux_x86_64.tar.gz
          mv ./sbatch /usr/local/bin/sbatch
          chmod 755 /usr/local/bin/sbatch

          echo "/usr/local/bin" >> $GITHUB_PATH
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            metrumresearchgroup/mrgmisc
            metrumresearchgroup/nmrec
            metrumresearchgroup/bbr
            any::pkgdown
            local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
